# Generated by Django 5.0.6 on 2024-06-17 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='localidad',
            new_name='sucursal',
        ),
    ]
